[versions]
agp = "8.13.2"
kotlin = "2.2.10"                   # "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.00"           # "2024.09.00"
# Kotlin Serialization
kotlinxSerialization = "1.7.3"
# Gson
gson = "2.13.2"
# Accompanist
accompanist = "0.34.0"              # "0.37.3"
# Icons extended
iconsExtended = "1.7.8"
# Coil
coil = "3.3.0"
# ViewModel
viewmodel-compose = "2.9.4"
lifecycleRuntimeCompose = "2.9.4"
# Retrofit 2
retrofit = "2.9.0"
converter-scalars = "2.9.0"
serialization-converter = "1.0.0"
# Okhttp3
okhttp = "4.11.0"
# Hilt
hiltVersion = "2.57.2"
hiltNavigationCompose = "1.3.0"
# Room
room-version = "2.8.2"
# Navigation
composeNavigation = "2.9.5"
# DataStore
datastorePreferences = "1.1.7"
# Services
lifecycleService = "2.9.4"
# Ksp
devtools-ksp = "2.2.10-2.0.2"
javaxInject = "1"
ui = "1.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# Kotlin Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
# Gson
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
# Accompanist
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
# Icons extended
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "iconsExtended" }
# Coil
coil-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
# ViewModel
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
# Retrofit 2
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
com-squareup-retrofit2-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converter-scalars" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "serialization-converter" }
# Okhttp3
com-squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
# Hilt
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android" , version.ref = "hiltVersion"}
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler" , version.ref = "hiltVersion"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-version" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-version" }
# Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation"}
# DataStore Preferences
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
# Services
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleRuntimeKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# Ksp para Hilt y Room
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
# Hilt
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }

